In [1]:
#Transforming data

In [2]:
import numpy as np
import pandas as pd
import copy
import math

#create a path to the file

file_path = "shopping.csv"

#read the csv file a pandas dataframe
df = pd.read_csv(file_path)

#print the dataframe column data types
df.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

In [3]:
df.head(5) #show first 10 data lines

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,3,142.500000,0,0.00,48,1052.255952,0.004348,0.013043,0.000000,0.0,Nov,1,8,6,11,Returning_Visitor,False,False
1,6,437.391304,2,235.55,83,2503.881781,0.002198,0.004916,2.086218,0.0,Mar,2,2,3,2,Returning_Visitor,False,True
2,1,41.125000,0,0.00,126,4310.004668,0.000688,0.012823,3.451072,0.0,Nov,2,2,2,2,Returning_Visitor,False,False
3,2,141.000000,0,0.00,10,606.666667,0.008333,0.026389,36.672294,0.0,Aug,2,5,7,4,Returning_Visitor,False,False
4,18,608.140000,6,733.80,168,4948.398759,0.006632,0.013528,10.150644,0.0,Aug,2,2,3,1,Returning_Visitor,True,False

In [4]:
#define a mapping scheme for the values not a number
bool_mapping={
    "TRUE":1,
    "FALSE":0
}

visitor_mapping={
    "Returning_Visitor":1,
    "New_Visitor":2,
    "Other":3
}

month_mapping={
    "Jan":1,
    "Feb":2,
    "Mar":3,
    "Apr":4,
    "May":5,
    "June":6,
    "Jul":7,
    "Aug":8,
    "Sep":9,
    "Oct":10,
    "Nov":11,
    "Dec":12
}

In [5]:

df['Revenue']=df['Revenue'].astype(str)
df['Weekend']=df['Weekend'].astype(str)
df['Revenue'] = df['Revenue'].str.upper()
df['Weekend'] = df['Weekend'].str.upper()

In [6]:
df.head(10)
df.dtypes #should be obkects due to the converion

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                     object
Revenue                     object
dtype: object

In [8]:
df['Month'] = df['Month'].replace(month_mapping)
df['VisitorType'] = df['VisitorType'].replace(visitor_mapping)
df['Revenue'] = df['Revenue'].replace(bool_mapping)  
df['Weekend'] = df['Weekend'].replace(bool_mapping)

In [9]:
df.head(10) #everything should be a interger / float now

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,3,142.500000,0,0.00,48,1052.255952,0.004348,0.013043,0.000000,0.0,11,1,8,6,11,1,0,0
1,6,437.391304,2,235.55,83,2503.881781,0.002198,0.004916,2.086218,0.0,3,2,2,3,2,1,0,1
2,1,41.125000,0,0.00,126,4310.004668,0.000688,0.012823,3.451072,0.0,11,2,2,2,2,1,0,0
3,2,141.000000,0,0.00,10,606.666667,0.008333,0.026389,36.672294,0.0,8,2,5,7,4,1,0,0
4,18,608.140000,6,733.80,168,4948.398759,0.006632,0.013528,10.150644,0.0,8,2,2,3,1,1,1,0
5,1,22.000000,0,0.00,9,415.250000,0.033333,0.048148,0.000000,0.0,3,3,3,1,1,1,0,0
6,0,0.000000,0,0.00,14,186.933333,0.042857,0.071429,0.000000,0.0,5,2,2,3,4,1,0,0
7,0,0.000000,0,0.00,12,198.000000,0.016667,0.075000,0.000000,0.0,3,2,2,3,2,1,0,0
8,8,149.500000,0,0.00,55,2598.991667,0.003279,0.008197,48.729956,0.0,5,2,4,8,2,1,1,0
9,6,140.333333,0,0.00,9,88.950000,0.000000,0.004762,0.000000,0.0,5,3,2,2,3,2,0,0

In [39]:
df.dtypes #everything should be a int / float now.

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                        int64
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                  int64
Weekend                      int64
Revenue                      int64
dtype: object

In [63]:
data_arr = df.to_numpy()

In [65]:
#Load the data in and save the mappings we did
X_train = df.iloc[:, :-1].values  # Assuming first columns are features, make these a numpy array, not a panda dataframe
y_train = df.iloc[:, -1].values   # Assuming the last column is the target (Revenue)

print(type(X_train))
#X_train = X_train.to_numpy()

print(X_train.shape)
print(y_train.shape)

<class 'numpy.ndarray'>
(5000, 17)

In [42]:
#MinMax Scaling
def min_max_scaling(data):
    scaled_data = data.copy()
    
    if len(data.shape) == 1:  # 1D array (like y_train)
        min_value = data.min()
        max_value = data.max()
        scaled_data = (data - min_value) / (max_value - min_value)
    
    else:  # 2D array (like X_train)
        for i in range(data.shape[1]):
            min_value = data[:, i].min()
            max_value = data[:, i].max()
            scaled_data[:, i] = (data[:, i] - min_value) / (max_value - min_value)
    
    return scaled_data

In [43]:
#implement the scale
X_train_minmax = min_max_scaling(X_train)
y_train_minmax = min_max_scaling(y_train)

In [44]:
#Mean Normalization Scaling
def mean_normalization(data):
    scaled_data = data.copy()
    
    if len(data.shape) == 1:  # Handle 1D array like y_train
        mean_value = data.mean()
        min_value = data.min()
        max_value = data.max()
        scaled_data = (data - mean_value) / (max_value - min_value)
    
    else:  # Handle 2D array like X_train
        for i in range(data.shape[1]):  # Loop through columns using NumPy's indexing
            mean_value = data[:, i].mean()
            min_value = data[:, i].min()
            max_value = data[:, i].max()
            scaled_data[:, i] = (data[:, i] - mean_value) / (max_value - min_value)
    
    return scaled_data

In [45]:
#implement the normalization scale
X_train_normal = mean_normalization(X_train)
y_train_normal = mean_normalization(y_train)

In [46]:
#Z-score normalization
def z_score_normalization(data):
    scaled_data = data.copy()
    
    if len(data.shape) == 1:  # Handle 1D array like y_train
        mean_value = data.mean()
        std_value = data.std()
        scaled_data = (data - mean_value) / std_value
    
    else:  # Handle 2D array like X_train
        for i in range(data.shape[1]):  # Loop through columns using NumPy's indexing
            mean_value = data[:, i].mean()
            std_value = data[:, i].std()
            scaled_data[:, i] = (data[:, i] - mean_value) / std_value
    
    return scaled_data

In [58]:
#implement z_score_normal
X_Train_Z = z_score_normalization(X_train)
y_Train_Z = z_score_normalization(y_train)

print(X_Train_Z)
print(X_train)

[[ 0.21173582  0.35206422 -0.38787235 ...  1.71636354 -0.39932615
  -0.55763754]
 [ 1.11273931  2.00864769  1.14643284 ... -0.51300172 -0.39932615
  -0.55763754]
 [-0.38893317 -0.21742069 -0.38787235 ... -0.51300172 -0.39932615
  -0.55763754]
 ...
 [-0.68926767 -0.44844478 -0.38787235 ... -0.76070897 -0.39932615
  -0.55763754]
 [-0.68926767 -0.44844478 -0.38787235 ... -0.51300172 -0.39932615
   1.79327957]
 [-0.08859868 -0.3866511  -0.38787235 ... -0.76070897 -0.39932615
  -0.55763754]]
[[  3.        142.5         0.        ...  11.          1.
    0.       ]
 [  6.        437.3913043   2.        ...   2.          1.
    0.       ]
 [  1.         41.125       0.        ...   2.          1.
    0.       ]
 ...
 [  0.          0.          0.        ...   1.          1.
    0.       ]
 [  0.          0.          0.        ...   2.          1.
    1.       ]
 [  2.         11.          0.        ...   1.          1.
    0.       ]]

In [48]:
#Logistic Regression Model

In [49]:
#Sigmoid function
def sigmoid(z):
    """
    Compute the sigmoid of z

    Args:
        z (ndarray): A scalar, numpy array of any size.

    Returns:
        g (ndarray): sigmoid(z), with the same shape as z
         
    """
          
    ### START CODE HERE ### 
    z = np.clip(z, -500, 500)  # Clip z to avoid overflow

    
    g = 1 / (1 + np.exp(-z))
    
    ### END SOLUTION ###  
    
    return g

In [50]:
def compute_cost(X, y, w, b, *argv):
    m, n = X.shape
    
    z = np.dot(X, w) + b
    print("z values:", z)  # Debugging line

    prediction = sigmoid(z)
    
  
    total_loss = 0

    for i in range(m):
        loss = -(y[i] * np.log(prediction[i]) + (1 - y[i]) * np.log(1 - prediction[i]))
        total_loss += loss

    total_cost = total_loss / m

    return total_cost

In [53]:
m,n = X_train.shape

initial_w = np.zeros(n)
initial_b = 0.
cost = compute_cost(X_Train_Z,y_Train_Z, initial_w, initial_b)
print('cost at initial w and b (zeros) {:.3f}'.format(cost))

z values: [0. 0. 0. ... 0. 0. 0.]
cost at initial w and b (zeros) 0.693

In [29]:
def compute_gradient(X, y, w, b, *argv):
    """
    Computes the gradient of the cost function.
    Args:
      X : (ndarray Shape (m,n)) data, m examples by n features
      y : (ndarray Shape (m,)) target value 
      w : (ndarray Shape (n,)) values of parameters of the model      
      b : (scalar) value of bias parameter of the model
    Returns:
      dj_dw : (ndarray Shape (n,)) gradient with respect to w
      dj_db : (scalar) gradient with respect to b
    """
    m, n = X.shape
    dj_dw = np.zeros_like(w)
    dj_db = 0.0

    # Compute gradient
    for i in range(m):
        z_wb = np.dot(X[i], w) + b
        f_wb = sigmoid(z_wb)
        error = f_wb - y[i]
        
        # Update gradients
        dj_dw += error * X[i]
        dj_db += error

    # Average the gradients
    dj_dw /= m
    dj_db /= m

    return dj_dw, dj_db

In [30]:
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters, lambda_): 
    """
    Performs batch gradient descent to learn theta. Updates theta by taking 
    num_iters gradient steps with learning rate alpha
    
    Args:
      X :    (ndarray Shape (m, n) data, m examples by n features
      y :    (ndarray Shape (m,))  target value 
      w_in : (ndarray Shape (n,))  Initial values of parameters of the model
      b_in : (scalar)              Initial value of parameter of the model
      cost_function :              function to compute cost
      gradient_function :          function to compute gradient
      alpha : (float)              Learning rate
      num_iters : (int)            number of iterations to run gradient descent
      lambda_ : (scalar, float)    regularization constant
      
    Returns:
      w : (ndarray Shape (n,)) Updated values of parameters of the model after
          running gradient descent
      b : (scalar)                Updated value of parameter of the model after
          running gradient descent
    """
    
    # number of training examples
    m = len(X)
    
    # An array to store cost J and w's at each iteration primarily for graphing later
    J_history = []
    w_history = []
    
    for i in range(num_iters):

        # Calculate the gradient and update the parameters
        dj_db, dj_dw = gradient_function(X, y, w_in, b_in, lambda_)   

        # Update Parameters using w, b, alpha and gradient
        w_in = w_in - alpha * dj_dw               
        b_in = b_in - alpha * dj_db              
       
        # Save cost J at each iteration
        if i<100000:      # prevent resource exhaustion 
            cost =  cost_function(X, y, w_in, b_in, lambda_)
            J_history.append(cost)

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters/10) == 0 or i == (num_iters-1):
            w_history.append(w_in)
            print(f"Iteration {i:4}: Cost {float(J_history[-1]):8.2f}   ")
        
    return w_in, b_in, J_history, w_history #return w and J,w history for graphing

In [31]:
np.random.seed(1)
num_features = X_train.shape[1]  # Get the number of features
initial_w = np.zeros(num_features)  # Start with zeros
initial_b = 0  # Initial bias (make sure this is a scalar)


# Some gradient descent settings
iterations = 150
alpha = 0.001  # Decrease the learning rate

# Run gradient descent
w, b, J_history, _ = gradient_descent(X_train, y_train, initial_w, initial_b, 
                                       compute_cost, compute_gradient, alpha, iterations, 0)

print("Final weights:", w)
print("Final bias:", b)

ValueError: operands could not be broadcast together with shapes (5000,) (17,)